apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: limits-validation-aws-lambda
  description: Lambda thats validate if a transaction is allowed by user limits.
  annotations:
   backstage.io/techdocs-ref: url:https://github.com/sebastian-quintana/backstage-poc
  links:
    - url: https://github.com/sebastian-quintana/backstage-poc
      title: GitHub Repo
      icon: github
  tags:
    - go
    - cupo-operativo
    - aws
    - lambda
spec:
  type: service
  lifecycle: production
  owner: transactional-team
  system: cupo-operativo
