apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: playlist-management
  description: Management of a playlist
  annotations:
   backstage.io/techdocs-ref: url:https://github.com/sebastian-quintana/backstage-poc
   github.com/project-slug: sebastian-quintana/backstage-poc
  links:
    - url: https://github.com/sebastian-quintana/backstage-poc
      title: GitHub Repo
      icon: github
  tags:
    - system
spec:
  type: service
  lifecycle: production
  owner: playlist-team
