site_name: 'Playlist lambda 1'

# Theme
theme:
  name: material
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Circular'
    code: 'Inconsolata'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
nav:
  - Home: index.md

plugins:
  - techdocs-core
